package com.avh.practicas.shared.evento;

public enum TipoEventoSistema {
    DOCENTE_ASESOR_CREADO,
    DOCENTE_ASESOR_ACTIVADO,
    DOCENTE_ASESOR_INACTIVADO,
    VACANTE_CREADA,
    VACANTE_APROBADA,
    VACANTE_RECHAZADA,
    VACANTE_PAUSADA,
    VACANTE_REACTIVADA,
    VACANTE_CERRADA,
    VACANTE_CUPOS_COMPLETOS,
    VINCULACION_CONFIRMADA,
    ENCUESTA_DISPONIBLE,
    RECORDATORIO_ENCUESTA
}
