export const estilosFiltros = {
  formCard: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
    padding: '12px 16px',
    background: '#f8fafc',
    borderRadius: 8,
    border: '1px solid #e5e7eb',
  },
  formInline: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 16,
  },
  input: {
    flex: 1,
    minWidth: 180,
    padding: '7px 12px',
    fontSize: 13,
    border: '1px solid #d1d5db',
    borderRadius: 6,
    outline: 'none',
    fontFamily: 'Arial, sans-serif',
  },
  inputCompacto: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 13,
    minWidth: 220,
  },
  select: {
    padding: '7px 12px',
    fontSize: 13,
    border: '1px solid #d1d5db',
    borderRadius: 6,
    outline: 'none',
    fontFamily: 'Arial, sans-serif',
    background: '#ffffff',
    cursor: 'pointer',
  },
  selectCompacto: {
    padding: '8px 12px',
    border: '1px solid #d1d5db',
    borderRadius: 8,
    fontSize: 13,
    background: '#fff',
    cursor: 'pointer',
  },
  btnBuscar: {
    padding: '7px 18px',
    background: '#2563eb',
    color: '#fff',
    border: 'none',
    borderRadius: 6,
    fontSize: 13,
    cursor: 'pointer',
    fontWeight: 600,
  },
  btnLimpiar: {
    padding: '7px 14px',
    background: '#f1f5f9',
    color: '#374151',
    border: '1px solid #d1d5db',
    borderRadius: 6,
    fontSize: 13,
    cursor: 'pointer',
  },
};
