package com.avh.practicas.correo.entity;

public enum TipoEventoCorreo {
    NUEVA_ASIGNACION,
    CAMBIO_ESTADO,
    ENCUESTA_DISPONIBLE,
    RECORDATORIO_ENCUESTA,
    ALERTA_INACTIVIDAD,
    CONFIRMACION_VINCULACION,
    RESULTADO_CIERRE,
    VACANTE_CREADA,
    VACANTE_APROBADA,
    VACANTE_RECHAZADA,
    DOCENTE_ASESOR_CREADO
}
